
  <m:item name='点卡产品分类' link='cards_type.php' rank='sys_Data' target='main' />
  <m:item name='点卡产品管理' link='cards_manage.php' rank='sys_Data' target='main' />
  <m:item name='会员产品分类' link='member_type.php' rank='sys_Data' target='main' />
  <m:item name='会员消费记录' link='member_operations.php' rank='sys_Data' target='main' />
  <m:item name='商店订单记录' link='shops_operations.php' rank='sys_Data' target='main' />
  <m:item name='支付接口设置' link='sys_payment.php' .php' rank='sys_Data' target='main' />
  <m:item name='配货方式设置' link='shops_delivery.php' rank='sys_Data' target='main' />
