<li>      				
					<h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
                    <p>[field:description/]...</p>
					<span>
					    <a href="[field:arcurl/]">[field:global.cfg_basehost/][field:arcurl/]</a>
						<small>分类：</small><a href="[field:typeurl/]" target="_blank">[field:typename/]</a>
						<small>点击：</small>[field:click/]
						<small>日期：</small>[field:stime/]
					</span>
				</li>