
    <m:item name='分类信息' ischannel='1' link='content_sg_list.php?channelid=-8' linkadd='archives_sg_add.php?channelid=-8' channelid='-8' rank='' target='main' />
  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='图片集' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='软件' ischannel='1' link='content_i_list.php?channelid=3' linkadd='soft_add.php?channelid=3' channelid='3' rank='' target='main' />
  <m:item name='商品' ischannel='1' link='content_list.php?channelid=6' linkadd='archives_add.php?channelid=6' channelid='6' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
