<?php
$z[0]=Array("global","",31,56);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","",515,538);
$z[1][4]['name']="id";
$z[2]=Array("global","",1004,1036);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1197,1229);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1388,1420);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("php","\r\n								for (\$i = 1; \$i < 12; \$i++)\r\n								{\r\n                                    \$isecheck = (\$i == 1) ? 'checked=\"1\" ' : '';\r\n								    echo '<li><input type=\"radio\" name=\"face\" value=\"'.\$i.'\" '.\$isecheck.'/><img src=\"'.\$cfg_templets_skin.'/images/mood/ico-mood-'.\$i.'.gif\" /></li>';\r\n								}\r\n								",1646,1979);
$z[6]=Array("php","\r\n								if(\$cfg_mb_open=='Y') {\r\n									echo '用户名:<input type=\"text\" name=\"username\" size=\"16\" class=\"ipt-txt\" style=\"text-transform: uppercase;\"/>';\r\n								}\r\n								",2298,2499);
$z[7]=Array("php","\r\n								if(preg_match(\"/4/\",\$safe_gdopen)){\r\n								echo '验证码:<input type=\"text\" name=\"validate\" size=\"4\" class=\"ipt-txt\" style=\"text-transform:uppercase;\"/><img src= \"'.\$cfg_cmspath.'/include/vdimgck.php\" id=\"validateimg\" style=\"cursor:pointer\" onclick=\"this.src=this.src+\\'?\\'\" title=\"点击我更换图片\" alt=\"点击我更换图片\" />';\r\n								 }\r\n                                ",2533,2951);
$z[8]=Array("php","\r\n								if(\$cfg_mb_open=='Y') {\r\n              		echo '<script language=\"javascript\" type=\"text/javascript\">CheckLogin();</script>';\r\n              	}\r\n							",3112,3294);
$z[9]=Array("field","",3703,3730);
$z[9][4]['name']="phpurl";
$z[10]=Array("field","",3748,3764);
$z[10][4]['name']="id";
$z[11]=Array("global","",4401,4426);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("global","",4571,4597);
$z[12][4]['name']="cfg_phpurl";
$z[13]=Array("field","",4635,4651);
$z[13][4]['name']="id";
$z[14]=Array("global","",4991,5016);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("global","",5946,5974);
$z[15][4]['name']="cfg_soft_lang";
$z[16]=Array("field","",6040,6056);
$z[16][4]['name']="id";
$z[17]=Array("global","",6399,6424);
$z[17][4]['name']="cfg_phpurl";
$z[18]=Array("global","",6563,6588);
$z[18][4]['name']="cfg_cmsurl";

?>