<dl class="tbox">
				<dt><strong>发布者资料</strong></dt>
				<dd>
					<a href="[field:spaceurl /]" class="userface"><img src="[field:face/]" width="52" height="52" /></a>
					<a href='[field:spaceurl /]' class="username">[field:uname/]</a>
					<span class="useract">
						<a href="[field:spaceurl /]" class="useract-vi">查看详细资料</a>
                        <a href="[field:spaceurl /]&action=guestbook" class="useract-pm">发送留言</a>
						<a href="[field:spaceurl /]&action=newfriend" class="useract-af">加为好友</a>
					</span>
					<span class="userinfo-sp"><small>用户等级:</small>[field:rankname /]</span>
					<span class="userinfo-sp"><small>注册时间:</small>[field:jointime function="MyDate('Y-m-d H:m',@me)"/]</span>
					<span class="userinfo-sp"><small>最后登录:</small>[field:logintime function="MyDate('Y-m-d H:m',@me)"/]</span>
				</dd>
			</dl>