<?php
$z[0]=Array("item","",4,89);
$z[0][4]['name']="模块管理";
$z[0][4]['link']="module_main.php";
$z[0][4]['rank']="sys_module";
$z[0][4]['target']="main";
$z[1]=Array("item","",93,183);
$z[1][4]['name']="上传新模块";
$z[1][4]['link']="module_upload.php";
$z[1][4]['rank']="sys_module";
$z[1][4]['target']="main";
$z[2]=Array("item","",187,278);
$z[2][4]['name']="模块生成向导";
$z[2][4]['link']="module_make.php";
$z[2][4]['rank']="sys_module";
$z[2][4]['target']="main";

?>