<?php
$z[0]=Array("global","",179,204);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",270,295);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",357,382);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",415,441);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",569,596);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",669,696);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",699,725);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",884,911);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",923,955);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1002,1028);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1083,1120);
$z[10][4]['name']="contentTopBanner1";
$z[11]=Array("myad","",1155,1192);
$z[11][4]['name']="contentTopBanner2";
$z[12]=Array("global","",1495,1520);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1560,1803);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",1895,1920);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2728,2858);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>