<?php
$z[0]=Array("global","",76,104);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("wintitle","",115,131);
$z[2]=Array("global","",186,220);
$z[2][4]['name']="cfg_plus_dir";
$z[3]=Array("global","",264,298);
$z[3][4]['name']="cfg_plus_dir";
$z[4]=Array("global","",516,550);
$z[4][4]['name']="cfg_plus_dir";
$z[5]=Array("wecome_info","",580,599);
$z[6]=Array("winform","",709,724);
$z[7]=Array("lang_cms_powerby","",776,800);

?>