<?php
return array (
  'site_closed' => '1',
  'site_name' => 'ThinkSNS',
  'site_slogan' => '为移动互联网添动力！',
  'site_header_keywords' => 'ThinkSNS a开源微博 免费微博 开源SNS',
  'site_header_description' => 'ThinkSNS开源微博程序致力于提供中国最好的微博程序、轻博客系统、SNS社交网络平台解决方案，提供微博源代码免费下载。内置微博插件机制和API体系，功能覆盖微群功能、社区群组、论坛微博整合、cms微博整合、长微博、图片微博、等综合功能，使微博二次开发更简单。系统采用php+mysql开发，开源发布，支持多个微博系统同步登陆，是能与ucenter整合的微博系统。智士软件使企业或个人快速拥有微博建站能力，为客户提供高质量的微博软件平台服务。',
  'site_company' => '',
  'site_footer' => '©2012 ZhishiSoft All Rights Reserved.',
  'site_footer_des' => 'ThinkSNS是智士软件旗下开源社交软件，适合懂技术的站长和软件公司基于系统进行二次开发商业使用请授权，个人使用请保留ThinkSNS标示。商业授权可直接来电咨询。',
  'site_logo' => '47635',
  'site_logo_w3g' => '',
  'site_qr_code' => '47634',
  'sina_weibo_link' => 'http://weibo.com/ithinksns',
  'login_bg' => '45095',
  'site_closed_reason' => '大伙儿不要害怕，我是来测试功能的，一会儿就给你们恢复，这个页面太丑了我要换一个。',
  'sys_domain' => 'admin,thinksns,kefu,liuxiaoqing,hujintao,liaosunan,xijinping,zhishisoft',
  'sys_nickname' => '管理员,超级管理员,法轮功,胡锦涛,江泽民,邓小平,小秘书,刘晓庆,廖素南,共产党,党,习近平,李宇春,政府,小胡祖宗,国民党,admin,智士软件,thinksns',
  'sys_email' => 'thinksns@zhishisoft.com',
  'home_page' => '0',
  'sys_version' => '2015050501',
  'site_online_count' => '1',
  'site_rewrite_on' => '0',
  'web_closed' => '1',
  'site_analytics_code' => 'PHNjcmlwdCBzcmM9Imh0dHA6Ly9zMTEuY256ei5jb20vc3RhdC5waHA/aWQ9MTI1NDkzMjcyNiZ3ZWJfaWQ9MTI1NDkzMjcyNiIgbGFuZ3VhZ2U9IkphdmFTY3JpcHQiPjwvc2NyaXB0Pg==',
  'logo' => 'http://127.0.0.1:8001/resources/theme/stv1/_static/image/logo.png',
  'home_url' => 'http://127.0.0.1:8001/index.php?app=public&mod=Index&act=index',
  'site_top_nav' => 
  array (
    7 => 
    array (
      'navi_id' => 7,
      'navi_name' => '朋友圈',
      'app_name' => 'public',
      'url' => 'http://127.0.0.1:8001/index.php?app=public',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 1,
    ),
    4 => 
    array (
      'navi_id' => 4,
      'navi_name' => '微吧+',
      'app_name' => 'weiba',
      'url' => 'http://127.0.0.1:8001/index.php?app=weiba',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 2,
    ),
    11 => 
    array (
      'navi_id' => 11,
      'navi_name' => '找伙伴',
      'app_name' => 'people',
      'url' => 'http://127.0.0.1:8001/index.php?app=people',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 3,
    ),
    2 => 
    array (
      'navi_id' => 2,
      'navi_name' => '频道',
      'app_name' => 'channel',
      'url' => 'http://127.0.0.1:8001/index.php?app=channel',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 4,
    ),
    48 => 
    array (
      'navi_id' => 48,
      'navi_name' => '官方动作',
      'app_name' => 'guanfang',
      'url' => 'http://demo.thinksns.com/ts4/index.php?app=weiba&mod=Index&act=detail&weiba_id=94',
      'target' => '_blank',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 8,
    ),
  ),
  'site_bottom_nav' => 
  array (
    40 => 
    array (
      'navi_id' => 40,
      'navi_name' => '关于我们',
      'app_name' => 'ABOUTUS',
      'url' => 'http://www.thinksns.com/about.html',
      'target' => '_blank',
      'status' => 1,
      'position' => '1',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 1,
    ),
    37 => 
    array (
      'navi_id' => 37,
      'navi_name' => 'TS 官网',
      'app_name' => 'TS',
      'url' => 'http://www.thinksns.com',
      'target' => '_blank',
      'status' => 1,
      'position' => '1',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 2,
    ),
    38 => 
    array (
      'navi_id' => 38,
      'navi_name' => '智士官网',
      'app_name' => 'zhishisoft',
      'url' => 'http://www.zhishisoft.com/',
      'target' => '_blank',
      'status' => 1,
      'position' => '1',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 3,
    ),
    39 => 
    array (
      'navi_id' => 39,
      'navi_name' => '联系我们',
      'app_name' => 'connect us',
      'url' => 'http://www.thinksns.com/buy.html',
      'target' => '_blank',
      'status' => 1,
      'position' => '1',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 4,
    ),
  ),
  'site_bottom_child_nav' => false,
  'site_guest_nav' => 
  array (
    12 => 
    array (
      'navi_id' => 12,
      'navi_name' => '首页',
      'app_name' => 'index',
      'url' => 'http://127.0.0.1:8001',
      'target' => '_self',
      'status' => 1,
      'position' => '2',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 1,
    ),
    14 => 
    array (
      'navi_id' => 14,
      'navi_name' => '广场',
      'app_name' => 'square',
      'url' => 'http://127.0.0.1:8001/index.php?app=square&mod=Index&act=index',
      'target' => '_self',
      'status' => 1,
      'position' => '2',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 2,
    ),
  ),
  'search_menu_list' => 
  array (
    0 => 
    array (
      'id' => 1,
      'app_name' => 'public',
      'app_id' => 0,
      'type' => '用户',
      'type_id' => 1,
    ),
    1 => 
    array (
      'id' => 2,
      'app_name' => 'public',
      'app_id' => 0,
      'type' => '分享',
      'type_id' => 2,
    ),
    2 => 
    array (
      'id' => 3,
      'app_name' => 'ask',
      'app_id' => 27,
      'type' => '问答',
      'type_id' => 1,
    ),
  ),
  'site_nav_apps' => 
  array (
    0 => 
    array (
      'app_id' => 25,
      'app_name' => 'square',
      'app_alias' => '广场',
      'description' => '',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://127.0.0.1:8001/index.php?app=square&mod=Index&act=index',
      'icon_url' => 'http://127.0.0.1:8001/apps/square/Appinfo/icon_app.png',
      'large_icon_url' => 'http://127.0.0.1:8001/apps/square/Appinfo/icon_app_large.png',
      'admin_entry' => 'square/Admin/index',
      'statistics_entry' => 'SquareStatistics/statistics',
      'display_order' => 25,
      'ctime' => 1415871528,
      'version' => '',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 0,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://127.0.0.1:8001/apps/square/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://127.0.0.1:8001/apps/square/Appinfo/icon_iphone.png',
      'android_icon' => 'http://127.0.0.1:8001/apps/square/Appinfo/icon_android.png',
    ),
    1 => 
    array (
      'app_id' => 5,
      'app_name' => 'channel',
      'app_alias' => '频道',
      'description' => '频道',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://127.0.0.1:8001/index.php?app=channel&mod=Index&act=index',
      'icon_url' => 'http://127.0.0.1:8001/apps/channel/Appinfo/icon_app.png',
      'large_icon_url' => 'http://127.0.0.1:8001/apps/channel/Appinfo/icon_app_large.png',
      'admin_entry' => 'channel/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 5,
      'ctime' => 1352520034,
      'version' => '',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 1,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://127.0.0.1:8001/apps/channel/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://127.0.0.1:8001/apps/channel/Appinfo/icon_iphone.png',
      'android_icon' => 'http://127.0.0.1:8001/apps/channel/Appinfo/icon_android.png',
    ),
    2 => 
    array (
      'app_id' => 4,
      'app_name' => 'people',
      'app_alias' => '找伙伴',
      'description' => '找人',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://127.0.0.1:8001/index.php?app=people&mod=Index&act=index',
      'icon_url' => 'http://127.0.0.1:8001/apps/people/Appinfo/icon_app.png',
      'large_icon_url' => 'http://127.0.0.1:8001/apps/people/Appinfo/icon_app_large.png',
      'admin_entry' => 'people/Admin/index',
      'statistics_entry' => '',
      'display_order' => 4,
      'ctime' => 1352512423,
      'version' => '',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 1,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://127.0.0.1:8001/apps/people/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://127.0.0.1:8001/apps/people/Appinfo/icon_iphone.png',
      'android_icon' => 'http://127.0.0.1:8001/apps/people/Appinfo/icon_android.png',
    ),
    3 => 
    array (
      'app_id' => 3,
      'app_name' => 'weiba',
      'app_alias' => '微吧',
      'description' => '微吧',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://127.0.0.1:8001/index.php?app=weiba&mod=Index&act=index',
      'icon_url' => 'http://127.0.0.1:8001/apps/weiba/Appinfo/icon_app.png',
      'large_icon_url' => 'http://127.0.0.1:8001/apps/weiba/Appinfo/icon_app_large.png',
      'admin_entry' => 'weiba/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 3,
      'ctime' => 1352256442,
      'version' => '1.0',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 1,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://127.0.0.1:8001/apps/weiba/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://127.0.0.1:8001/apps/weiba/Appinfo/icon_iphone.png',
      'android_icon' => 'http://127.0.0.1:8001/apps/weiba/Appinfo/icon_android.png',
    ),
  ),
  'langJsList' => 
  array (
    0 => 'http://127.0.0.1:8001/data/lang/public_zh-cn.js',
  ),
  'initNums' => '140',
);
?>