version: '2'
services:
  php5-cltphp_5.5.2:
    build: ./php-fpm
    image: s1r1u5/cltphp:5.5.2
    restart: always
    links: 
        - mysql_cltphp_5.5.2:db
    ports:
        - 8002:80
    depends_on:
        - mysql_cltphp_5.5.2

  mysql_cltphp_5.5.2:
    build: ./mysql
    image: s1r1u5/mysql_cltphp:5.5.2
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

