<?php
$names = array (
  'article' => '文章模板',
  'brand' => '品牌模板',
  'buy' => '求购模板',
  'chip' => '模板片断',
  'city' => '城市分站',
  'club' => '商圈模板',
  'company' => '公司模板',
  'down' => '下载模板',
  'exhibit' => '展会模板',
  'extend' => '功能扩展',
  'footer' => '全站页脚',
  'group' => '团购模板',
  'header' => '全站页头',
  'homepage' => '公司主页',
  'index' => '网站首页',
  'info' => '信息模板',
  'job' => '人才模板',
  'know' => '知道模板',
  'mail' => '邮件模板',
  'mall' => '商城模板',
  'member' => '商务中心',
  'message' => '提示信息',
  'photo' => '图库模板',
  'quote' => '行情模板',
  'sell' => '供应模板',
  'special' => '专题模板',
  'tag' => '标签模板',
  'video' => '视频模板',
);
?>