version: '2'
services:
  php5-seacms_6.45:
    build: ./php-fpm
    image: s1r1u5/seacms:6.45
    restart: always
    links: 
        - mysql_seacms_6:db
    ports:
        - 8002:80
    depends_on:
        - mysql_seacms_6

  mysql_seacms_6:
    build: ./mysql
    image: s1r1u5/mysql_seacms:6.45
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

