version: '3'
services:
   rails:
      image: sprockets:3.7.1
      build: ./web
      restart: always
      networks:
         extnetwork:
            ipv4_address: 172.168.0.2
      ports:
         - 3000:3000
networks:
   extnetwork:
      ipam:
         config:
         - subnet: 172.168.0.1/24


