<?php
/*
[eval]
admin/include/global.func.php="1";
include/global.func.php="1";
admin/include/pclzip.lib.php="1";
admin/set/pclzip.lib.php="1";
update/pclzip.lib.php="1";
[fsockopen]
include/mail/class.smtp.php="1";
admin/include/global.func.php="1";
admin/system/basic.php="1";
include/export.func.php="1";
update/func.php="1";
include/alipay/lib/alipay_core.function.php="1";
install/index.php="1";
[cmd]
include/mail/class.phpmailer.php="1";
[exec]
admin/include/global.func.php="1";
include/export.func.php="1";
include/stat/stat.php="1";
[scandir]
admin/include/global.func.php="1";
admin/ckfinder/core/connector/php/php5/Utils/FileSystem.php="1";
admin/ckeditor/ckfinder/core/connector/php/php5/Utils/FileSystem.php="1";
admin/seo/sethtm.php="1";
admin/set/sethtm.php="1";
[pfsockopen]
include/export.func.php="1";
include/mail/class.smtp.php="1";
update/func.php="1";
install/index.php="1";
[shell_exec]
fckeditor/editor/dialog/fck_spellerpages/spellerpages/server-scripts/spellchecker.php="1";
[size]
admin/app/shop/admin/app/shop/setapp.php="1";
admin/app/website/admin/app/website/setapp.php="1";
admin/app/share/admin/app/share/share.php="1";
[encryption]
admin/app/shop/include/alipay/return_url.php="1";
admin/app/shop/include/alipay/notify_url.php="1";
*/
?>