<?php
$metadmin[categorynamemark]=0; 
$metadmin[categorymarkimage]=1; 
$metadmin[categoryimage]=1; 
$metadmin[homecontent]=1; 
$metadmin[newsimage]=1; 
$metadmin[newscom]=1;
$metadmin[productnew]=0; 
$metadmin[productcom]=1; 
$metadmin[imgnew]=0;
$metadmin[imgcom]=1;
$metadmin[downloadnew]=0;
$metadmin[downloadcom]=1;
?>