<?php
$metadmin[categorynamemark]=0;
$metadmin[categorymarkimage]=0;
$metadmin[categoryimage]=0;
$metadmin[homecontent]=1;
$metadmin[newsimage]=1;
$metadmin[newscom]=1;
$metadmin[productnew]=1;
$metadmin[productcom]=1;
$metadmin[imgnew]=0;
$metadmin[imgcom]=1;
$metadmin[downloadnew]=0;
$metadmin[downloadcom]=1;
$metadmin[pagename]=0;
$metadmin[productother]=0;
$metadmin[imgother]=0;
?>