<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'572R6aG15Z+656GA');
$cfg_Cs[2]=array(1,1,1,'SFRNTA==');
$cfg_Cs[3]=array(1,1,1,'RElWJkNTUw==');
$cfg_Cs[4]=array(1,1,1,'SmF2YXNjcmlwdC9BamF4');
$cfg_Cs[5]=array(1,1,1,'RHJlYW13ZWF2ZXI=');
$cfg_Cs[6]=array(0,2,1,'56uZ6ZW/5Zu+6ZuG');
$cfg_Cs[7]=array(0,3,1,'6L2v5Lu25LiL6L29');
$cfg_Cs[8]=array(0,6,1,'5ZWG5ZOB6ZSA5ZSu');
$cfg_Cs[9]=array(0,-8,1,'5YiG57G75L+h5oGv');
$cfg_Cs[10]=array(0,1,1,'57uH5qKmQ01T');
$cfg_Cs[11]=array(0,1,1,'5biu5Yqp5paH5qGj');
?>