<?php
$metadmin[categorynamemark]=1; 
$metadmin[categorymarkimage]=1; 
$metadmin[categoryimage]=1; 
$metadmin[homecontent]=1; 
$metadmin[newsimage]=1; 
$metadmin[newscom]=1; 
$metadmin[productnew]=1;
$metadmin[productcom]=1; 
$metadmin[imgnew]=1; 
$metadmin[imgcom]=1; 
$metadmin[downloadnew]=1; 
$metadmin[downloadcom]=1; 
$metadmin[pagename]=0;
?>